CC = gcc
CFLAGS = -std=c11 -Wall -Wextra -pedantic -g

all: Week3Jason Week4Jason

Week3Jason: Week3Jason.c
	$(CC) $(CFLAGS) -o Week3Jason Week3Jason.c


Week4Jason: Week4Jason.c
	$(CC) $(CFLAGS) -o Week4Jason Week4Jason.c

clean:
	rm -f Week3Jason Week4Jason
