CC = gcc
CFLAGS = -std=c11 -Wall -Wextra -pedantic -g

all: Week3Jason Week4Jason Week4pt2

Week3Jason: Week3Jason.c
	$(CC) $(CFLAGS) -o Week3Jason Week3Jason.c


Week4Jason: Week4Jason.c
	$(CC) $(CFLAGS) -o Week4Jason Week4Jason.c

Week4pt2: Week4pt2.c
	$(CC) $(CFLAGS) -o Week4pt2 Week4pt2.c

clean:
	rm -f Week3Jason Week4Jason Week4pt2
