CC = gcc
CFLAGS = -std=c11 -Wall -Werror -Wextra -pedantic -g

all: Week3Jason Hexabite

Week3Jason: Week3Jason.c
	$(CC) $(CFLAGS) -o Week3Jason Week3Jason.c

Hexabite: Hexabite.c
	$(CC) $(CFLAGS) -o Hexabite Hexabite.c


clean:
	rm -f Week3Jason Hexabite
